# This is a basic workflow to help you get started with Actions

name: Deploying to server

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the $default-branch branch
  push:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    
  sync:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - uses: up9cloud/action-rsync@master
        env:
          HOST: ${{secrets.HOST}}
          USER: ${{secrets.USER}}
          PASSWORD: ${{secrets.PASS}}
          TARGET: ${{secrets.PATH}}
          # PRE_SCRIPT: "docker-compose down"
          # POST_SCRIPT: "docker-compose up -d"

  restart:
    needs: sync
    runs-on: ubuntu-latest

    steps:

    - name: executing remote ssh 
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.DSM_USER }}
        key: ${{ secrets.DSM_KEY }}
        port: ${{ secrets.DSM_PORT }}
        script: exec bash -l -c "cd /volume1/EducPop && docker-compose down && docker-compose up -d"