name: Deploying to server

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
    
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Update the sources
        uses: up9cloud/action-rsync@master
        env:
          HOST: ${{secrets.HOST}}
          USER: ${{secrets.USER}}
          PASSWORD: ${{secrets.PASS}}
          TARGET: ${{secrets.PATH}}

  restart:
    needs: sync
    runs-on: ubuntu-latest
    steps:
    - name: Restart the app (SSH)
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.DSM_USER }}
        key: ${{ secrets.DSM_KEY }}
        port: ${{ secrets.DSM_PORT }}
        script: exec bash -l -c "cd /volume1/EducPop && docker-compose up -d --build --force-recreate"